import { test, expect, Page, TestInfo, APIRequestContext } from '@playwright/test';
import * as allure from 'allure-js-commons';
export const base=process.env.QA_URL||'http://localhost:18081';
export async function given(page:Page,screen:string,branch:string){await allure.epic('1호선톤 품질 검증');await allure.feature(screen);await allure.story(branch);test.info().annotations.push({type:'screen',description:screen},{type:'branch',description:branch});await test.step('Given · 실제 SQLite 테스트 서버를 초기화한다',async()=>{const r=await page.request.post('/__test/reset',{headers:{'X-Test-Key':'test-only-local'}});expect(r.ok()).toBeTruthy();});}
export async function login(page:Page,role='investor',code=role==='admin'?'4821':'0037'){return test.step('When · '+(role==='admin'?'관리자':'투자자')+' 코드로 실제 로그인',async()=>{await page.goto(role==='admin'?'/admin/login':'/login');await expect(page.locator('#code')).toBeVisible();await page.locator('#code').fill(code);await page.locator('#login-button').click();await expect(page).toHaveURL(role==='admin'?/\/admin$/:/\/invest$/);await expect(page.locator(role==='admin'?'#metrics':'#balance-card')).not.toContainText('불러오는');if(role==='admin')await expect(page.locator('#metrics .metric')).toHaveCount(6);else await expect(page.locator('[data-team]')).toHaveCount(20);});}
export async function invest(page:Page,team:number,amount:number){return test.step(`When · 팀${team}에 ${amount/10000}만원 선택·모달 확인·투자 확정`,async()=>{await page.goto('/invest/teams/'+team);await page.locator(`[data-amount="${amount}"]`).click();await page.locator('#next').click();await page.locator('#confirm-send').click();await expect(page).toHaveURL(/\/invest\/success\//);await expect(page.locator('#success-balance')).toContainText('원');});}
export async function capture(page:Page,label:string,components:Record<string,string>={}){await test.step('Then · '+label,async()=>{await page.evaluate(()=>{document.querySelectorAll('.qa-marker').forEach(x=>x.remove());const modal=document.querySelector('dialog[open]');const root=modal||document;for(const el of root.querySelectorAll<HTMLElement>('[data-qa]')){const r=el.getBoundingClientRect();if(!r.width||!r.height)continue;const mark=document.createElement('span');mark.className='qa-marker';mark.textContent=el.dataset.qa||'';mark.style.left=Math.min(r.right-16,document.documentElement.clientWidth-26)+window.scrollX+'px';mark.style.top=Math.max(r.top-8,0)+window.scrollY+'px';(modal||document.body).append(mark);if(modal){const mr=modal.getBoundingClientRect();mark.style.left=(r.right-mr.left-16)+'px';mark.style.top=(r.top-mr.top-8)+'px';}}});const png=await page.screenshot({fullPage:true,animations:'disabled'});await test.info().attach(label,{body:png,contentType:'image/png'});await test.info().attach('번호별 검증 내용',{body:Buffer.from(JSON.stringify(components,null,2)),contentType:'application/json'});await page.evaluate(()=>document.querySelectorAll('.qa-marker').forEach(x=>x.remove()));});}
export async function direct(page:Page,path:string,method='GET',body?:unknown,key?:string){return page.evaluate(async({path,method,body,key})=>{const role=path.startsWith('/admin')?'admin':'investor';const s=await fetch('/api/v1/'+role+'/session').then(r=>r.json());const r=await fetch('/api/v1'+path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':s.csrfToken||'',...(key?{'Idempotency-Key':key}:{})},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:r.status===204?null:await r.json()};},{path,method,body,key});}
export async function evidence(value:unknown,label='API 검증 결과'){await test.info().attach(label,{body:Buffer.from(JSON.stringify(value,null,2)),contentType:'application/json'});}
export async function apiLogin(request:APIRequestContext,role='investor',code=role==='admin'?'4821':'0037'){const p=await request.get('/api/v1/'+role+'/csrf');const c=await p.json();const r=await request.post('/api/v1/'+role+'/session',{headers:{Origin:base,'X-CSRF-Token':c.csrfToken},data:{code}});expect(r.status()).toBe(200);return r.json();}
